### PR TITLE
Tweak docs a bit more

### PR DESCRIPTION
**Pull request by NickCrews**
See https://github.com/dedupeio/dedupe/issues/948

### CODE REVIEW

**Comment by NickCrews** [comment]
Not sure why that CI failed, looks external to this patch.

Weirdly, got the same error trying to import numpy in https://github.com/dedupeio/dedupe/runs/4970736852?check_suite_focus=true, but that CI run succeeded?

**Comment by NickCrews** [comment]
Looking at the [logs of a recent successful build](https://github.com/dedupeio/dedupe/runs/4970736852?check_suite_focus=true), looks like it's only a problem for python 3.10. In that run, CI tried to build fastcluster 1.2.4, failed, then kept on downgrading versions of fastcluster until it finally succeeded with fastcluster 1.1.25.

Here is [the diff between 1.1.25 -> 1.1.26](https://github.com/dmuellner/fastcluster/compare/v1.1.25...v1.1.26), not sure yet what the actual problem is...

**Comment by NickCrews** [comment]
Moved that CI problem into its own issue

**Comment by fgregg** [comment]
thanks!

**Pull request merged**
